name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "discord-umbrellabot" #Must be unique in Heroku
          heroku_email: "jpewpoopachew@gmail.com"
        env:
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          GUILD_ID: ${{secrets.GUILD_ID}}
          OUTPUT_CHANNEL_ID: ${{secrets.OUTPUT_CHANNEL_ID}}
          PING_ROLE_ID: ${{secrets.PING_ROLE_ID}}